/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

import javax.swing.ImageIcon;

/**
 *
 * @author luayon
 */
public class GamePlay extends javax.swing.JFrame {

    private Student currentStudent; // to keep track of the current student
    private int score;

    /**
     * Creates new form test
     */
    public GamePlay() {
        initComponents();
        score = 1;

        // Ensure the tab starts at index 0
        jTabbedPane1.setSelectedIndex(0);

        updateScoreLabels();

    }

    // Method to handle common functionality for displaying student images
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HideBar = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        NotePanel = new javax.swing.JPanel();
        ScoreBoardPanel = new javax.swing.JPanel();
        AddPointsLabel1 = new javax.swing.JLabel();
        CurrentPointsLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DosRulesAndRegulation = new javax.swing.JButton();
        RulesAndRegulation = new javax.swing.JButton();
        StudentPass = new javax.swing.JButton();
        EntryPass = new javax.swing.JButton();
        NoteImage = new javax.swing.JLabel();
        RuleBookPanel = new javax.swing.JPanel();
        ScoreBoardPanel1 = new javax.swing.JPanel();
        AddPointsLabel2 = new javax.swing.JLabel();
        CurrentPointsLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OpenBasicRules = new javax.swing.JButton();
        OpenStudents = new javax.swing.JButton();
        OpenMap = new javax.swing.JButton();
        Note1 = new javax.swing.JButton();
        StudentPass1 = new javax.swing.JButton();
        EntryPass1 = new javax.swing.JButton();
        MapBookamark = new javax.swing.JButton();
        BookmarkRules = new javax.swing.JButton();
        BookamarkStudent = new javax.swing.JButton();
        RuleBookImage = new javax.swing.JLabel();
        StudentPassPanel = new javax.swing.JPanel();
        ScoreBoardPanel2 = new javax.swing.JPanel();
        AddPointsLabel3 = new javax.swing.JLabel();
        CurrentPointsLabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RulesAndRegulation2 = new javax.swing.JButton();
        Note2 = new javax.swing.JButton();
        EntryPass2 = new javax.swing.JButton();
        Score = new javax.swing.JLabel();
        SHANTAY = new javax.swing.JButton();
        SASHAY = new javax.swing.JButton();
        StudentPassImage = new javax.swing.JLabel();
        StudentLetterPanel = new javax.swing.JPanel();
        ScoreBoardPanel3 = new javax.swing.JPanel();
        AddPointsLabel4 = new javax.swing.JLabel();
        CurrentPointsLabel4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Note3 = new javax.swing.JButton();
        RulesAndRegulation3 = new javax.swing.JButton();
        StudentPass3 = new javax.swing.JButton();
        SHANTAY3 = new javax.swing.JButton();
        SASHAY4 = new javax.swing.JButton();
        StudentNameLabel = new javax.swing.JLabel();
        StudentNumberLabel = new javax.swing.JLabel();
        StudentCourseLabel = new javax.swing.JLabel();
        StudentContactLabel = new javax.swing.JLabel();
        StudentLetterImage = new javax.swing.JLabel();
        ShantayPanel = new javax.swing.JPanel();
        ScoreBoardPanel4 = new javax.swing.JPanel();
        AddPointsLabel5 = new javax.swing.JLabel();
        CurrentPointsLabel5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Note4 = new javax.swing.JButton();
        RulesAndRegulation4 = new javax.swing.JButton();
        EntryPass3 = new javax.swing.JButton();
        NextStudentButton = new javax.swing.JButton();
        SASHAY2 = new javax.swing.JButton();
        StudentShantay = new javax.swing.JLabel();
        SashayPanel = new javax.swing.JPanel();
        ScoreBoardPanel9 = new javax.swing.JPanel();
        AddPointsLabel6 = new javax.swing.JLabel();
        CurrentPointsLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Note5 = new javax.swing.JButton();
        RulesAndRegulation5 = new javax.swing.JButton();
        NextStudentButton1 = new javax.swing.JButton();
        EntryPass4 = new javax.swing.JButton();
        SHANTAY2 = new javax.swing.JButton();
        StudentSashay = new javax.swing.JLabel();
        GameOverPanel = new javax.swing.JPanel();
        ScoreLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HideBar.setBackground(new java.awt.Color(158, 113, 147));
        HideBar.setForeground(new java.awt.Color(158, 113, 147));
        getContentPane().add(HideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 700, 40));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        NotePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreBoardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPointsLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AddPointsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        AddPointsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddPointsLabel1.setText("0");
        ScoreBoardPanel.add(AddPointsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, -1));

        CurrentPointsLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        CurrentPointsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPointsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPointsLabel1.setText("0");
        ScoreBoardPanel.add(CurrentPointsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_5533.jpg"))); // NOI18N
        ScoreBoardPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        NotePanel.add(ScoreBoardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 40, 210, 30));

        DosRulesAndRegulation.setContentAreaFilled(false);
        DosRulesAndRegulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosRulesAndRegulationActionPerformed(evt);
            }
        });
        NotePanel.add(DosRulesAndRegulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 130, 400));

        RulesAndRegulation.setContentAreaFilled(false);
        RulesAndRegulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesAndRegulationActionPerformed(evt);
            }
        });
        NotePanel.add(RulesAndRegulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 90, 100));

        StudentPass.setContentAreaFilled(false);
        StudentPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPassActionPerformed(evt);
            }
        });
        NotePanel.add(StudentPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 90, 110));

        EntryPass.setContentAreaFilled(false);
        EntryPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPassActionPerformed(evt);
            }
        });
        NotePanel.add(EntryPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 90, 130));

        NoteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/TABLE (2).png"))); // NOI18N
        NotePanel.add(NoteImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jTabbedPane1.addTab("tab1", NotePanel);

        RuleBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreBoardPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPointsLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AddPointsLabel2.setForeground(new java.awt.Color(255, 255, 255));
        AddPointsLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddPointsLabel2.setText("0");
        ScoreBoardPanel1.add(AddPointsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, -1));

        CurrentPointsLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        CurrentPointsLabel2.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPointsLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPointsLabel2.setText("0");
        ScoreBoardPanel1.add(CurrentPointsLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_5533.jpg"))); // NOI18N
        ScoreBoardPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        RuleBookPanel.add(ScoreBoardPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 40, 210, 30));

        OpenBasicRules.setContentAreaFilled(false);
        OpenBasicRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBasicRulesActionPerformed(evt);
            }
        });
        RuleBookPanel.add(OpenBasicRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 130, 30));

        OpenStudents.setContentAreaFilled(false);
        OpenStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenStudentsActionPerformed(evt);
            }
        });
        RuleBookPanel.add(OpenStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 110, 20));

        OpenMap.setContentAreaFilled(false);
        OpenMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMapActionPerformed(evt);
            }
        });
        RuleBookPanel.add(OpenMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 20));

        Note1.setContentAreaFilled(false);
        Note1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note1ActionPerformed(evt);
            }
        });
        RuleBookPanel.add(Note1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 70, 110));

        StudentPass1.setContentAreaFilled(false);
        StudentPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPass1ActionPerformed(evt);
            }
        });
        RuleBookPanel.add(StudentPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 90, 110));

        EntryPass1.setContentAreaFilled(false);
        EntryPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPass1ActionPerformed(evt);
            }
        });
        RuleBookPanel.add(EntryPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 80, 130));

        MapBookamark.setContentAreaFilled(false);
        MapBookamark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapBookamarkActionPerformed(evt);
            }
        });
        RuleBookPanel.add(MapBookamark, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 110, 30));

        BookmarkRules.setContentAreaFilled(false);
        BookmarkRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookmarkRulesActionPerformed(evt);
            }
        });
        RuleBookPanel.add(BookmarkRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, 30));

        BookamarkStudent.setContentAreaFilled(false);
        BookamarkStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookamarkStudentActionPerformed(evt);
            }
        });
        RuleBookPanel.add(BookamarkStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 110, 30));

        RuleBookImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RULES AND REGULATION (1).png"))); // NOI18N
        RuleBookPanel.add(RuleBookImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jTabbedPane1.addTab("tab2", RuleBookPanel);

        StudentPassPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreBoardPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPointsLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AddPointsLabel3.setForeground(new java.awt.Color(255, 255, 255));
        AddPointsLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddPointsLabel3.setText("0");
        ScoreBoardPanel2.add(AddPointsLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, -1));

        CurrentPointsLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        CurrentPointsLabel3.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPointsLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPointsLabel3.setText("0");
        ScoreBoardPanel2.add(CurrentPointsLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_5533.jpg"))); // NOI18N
        ScoreBoardPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        StudentPassPanel.add(ScoreBoardPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 40, 210, 30));

        RulesAndRegulation2.setContentAreaFilled(false);
        RulesAndRegulation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesAndRegulation2ActionPerformed(evt);
            }
        });
        StudentPassPanel.add(RulesAndRegulation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 80, 90));

        Note2.setContentAreaFilled(false);
        Note2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note2ActionPerformed(evt);
            }
        });
        StudentPassPanel.add(Note2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 70, 110));

        EntryPass2.setContentAreaFilled(false);
        EntryPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPass2ActionPerformed(evt);
            }
        });
        StudentPassPanel.add(EntryPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 80, 130));

        Score.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Score.setForeground(new java.awt.Color(255, 255, 255));
        StudentPassPanel.add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 80, 30));

        SHANTAY.setContentAreaFilled(false);
        SHANTAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHANTAYActionPerformed(evt);
            }
        });
        StudentPassPanel.add(SHANTAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, 30));

        SASHAY.setContentAreaFilled(false);
        SASHAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SASHAYActionPerformed(evt);
            }
        });
        StudentPassPanel.add(SASHAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 30));

        StudentPassImage.setBackground(new java.awt.Color(158, 113, 147));
        StudentPassImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESIZED CHARACTERS/AISHA.png"))); // NOI18N
        StudentPassPanel.add(StudentPassImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab3", StudentPassPanel);

        StudentLetterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreBoardPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPointsLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AddPointsLabel4.setForeground(new java.awt.Color(255, 255, 255));
        AddPointsLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddPointsLabel4.setText("0");
        ScoreBoardPanel3.add(AddPointsLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, -1));

        CurrentPointsLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        CurrentPointsLabel4.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPointsLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPointsLabel4.setText("0");
        ScoreBoardPanel3.add(CurrentPointsLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_5533.jpg"))); // NOI18N
        ScoreBoardPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        StudentLetterPanel.add(ScoreBoardPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 40, 210, 30));

        Note3.setContentAreaFilled(false);
        Note3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note3ActionPerformed(evt);
            }
        });
        StudentLetterPanel.add(Note3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 70, 110));

        RulesAndRegulation3.setContentAreaFilled(false);
        RulesAndRegulation3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesAndRegulation3ActionPerformed(evt);
            }
        });
        StudentLetterPanel.add(RulesAndRegulation3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 90, 100));

        StudentPass3.setContentAreaFilled(false);
        StudentPass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPass3ActionPerformed(evt);
            }
        });
        StudentLetterPanel.add(StudentPass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 90, 120));

        SHANTAY3.setContentAreaFilled(false);
        SHANTAY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHANTAY3ActionPerformed(evt);
            }
        });
        StudentLetterPanel.add(SHANTAY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, 30));

        SASHAY4.setBackground(new java.awt.Color(172, 148, 178));
        SASHAY4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        SASHAY4.setContentAreaFilled(false);
        SASHAY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SASHAY4ActionPerformed(evt);
            }
        });
        StudentLetterPanel.add(SASHAY4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 30));

        StudentNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StudentNameLabel.setForeground(new java.awt.Color(172, 146, 175));
        StudentNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentNameLabel.setText("AISHA");
        StudentLetterPanel.add(StudentNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 130, 30));

        StudentNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StudentNumberLabel.setForeground(new java.awt.Color(159, 151, 147));
        StudentNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentNumberLabel.setText("2014-26");
        StudentLetterPanel.add(StudentNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 130, 20));

        StudentCourseLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        StudentCourseLabel.setForeground(new java.awt.Color(172, 146, 175));
        StudentCourseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentCourseLabel.setText("BS FAR");
        StudentLetterPanel.add(StudentCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 90, 30));

        StudentContactLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        StudentContactLabel.setForeground(new java.awt.Color(172, 146, 175));
        StudentContactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentContactLabel.setText("09987123456");
        StudentLetterPanel.add(StudentContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 90, 30));

        StudentLetterImage.setBackground(new java.awt.Color(158, 113, 147));
        StudentLetterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ENTRY PERMIT/AISHA.png"))); // NOI18N
        StudentLetterPanel.add(StudentLetterImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab4", StudentLetterPanel);

        ShantayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreBoardPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPointsLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AddPointsLabel5.setForeground(new java.awt.Color(255, 255, 255));
        AddPointsLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddPointsLabel5.setText("0");
        ScoreBoardPanel4.add(AddPointsLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, -1));

        CurrentPointsLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        CurrentPointsLabel5.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPointsLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPointsLabel5.setText("0");
        ScoreBoardPanel4.add(CurrentPointsLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_5533.jpg"))); // NOI18N
        ScoreBoardPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        ShantayPanel.add(ScoreBoardPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 40, 210, 30));

        Note4.setContentAreaFilled(false);
        Note4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note4ActionPerformed(evt);
            }
        });
        ShantayPanel.add(Note4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 70, 110));

        RulesAndRegulation4.setContentAreaFilled(false);
        RulesAndRegulation4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesAndRegulation4ActionPerformed(evt);
            }
        });
        ShantayPanel.add(RulesAndRegulation4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 80, 90));

        EntryPass3.setContentAreaFilled(false);
        EntryPass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPass3ActionPerformed(evt);
            }
        });
        ShantayPanel.add(EntryPass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 80, 130));

        NextStudentButton.setContentAreaFilled(false);
        NextStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStudentButtonActionPerformed(evt);
            }
        });
        ShantayPanel.add(NextStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 650, 90, 60));

        SASHAY2.setContentAreaFilled(false);
        SASHAY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SASHAY2ActionPerformed(evt);
            }
        });
        ShantayPanel.add(SASHAY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 100, 30));

        StudentShantay.setBackground(new java.awt.Color(158, 113, 147));
        StudentShantay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESIZED CHARACTERS/AISHA IN.png"))); // NOI18N
        ShantayPanel.add(StudentShantay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("SHANTAY", ShantayPanel);

        SashayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreBoardPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPointsLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        AddPointsLabel6.setForeground(new java.awt.Color(255, 255, 255));
        AddPointsLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AddPointsLabel6.setText("0");
        ScoreBoardPanel9.add(AddPointsLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 30, -1));

        CurrentPointsLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        CurrentPointsLabel6.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPointsLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CurrentPointsLabel6.setText("0");
        ScoreBoardPanel9.add(CurrentPointsLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_5533.jpg"))); // NOI18N
        ScoreBoardPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        SashayPanel.add(ScoreBoardPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 40, 210, 30));

        Note5.setContentAreaFilled(false);
        Note5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Note5ActionPerformed(evt);
            }
        });
        SashayPanel.add(Note5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 70, 110));

        RulesAndRegulation5.setContentAreaFilled(false);
        RulesAndRegulation5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesAndRegulation5ActionPerformed(evt);
            }
        });
        SashayPanel.add(RulesAndRegulation5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 80, 90));

        NextStudentButton1.setContentAreaFilled(false);
        NextStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStudentButton1ActionPerformed(evt);
            }
        });
        SashayPanel.add(NextStudentButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, 90, 60));

        EntryPass4.setContentAreaFilled(false);
        EntryPass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPass4ActionPerformed(evt);
            }
        });
        SashayPanel.add(EntryPass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 80, 130));

        SHANTAY2.setContentAreaFilled(false);
        SHANTAY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHANTAY2ActionPerformed(evt);
            }
        });
        SashayPanel.add(SHANTAY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, 30));

        StudentSashay.setBackground(new java.awt.Color(158, 113, 147));
        StudentSashay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RESIZED CHARACTERS/AISHA OUT.png"))); // NOI18N
        SashayPanel.add(StudentSashay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("SHASAY", SashayPanel);

        GameOverPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ScoreLabel.setForeground(new java.awt.Color(255, 142, 129));
        ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GameOverPanel.add(ScoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 80, 60));

        NextButton.setContentAreaFilled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        GameOverPanel.add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 150, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/POINTS SCREEN.png"))); // NOI18N
        GameOverPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("GAMEOVER", GameOverPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DosRulesAndRegulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosRulesAndRegulationActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_DosRulesAndRegulationActionPerformed

    private void RulesAndRegulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesAndRegulationActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_RulesAndRegulationActionPerformed

    private void Note1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Note1ActionPerformed

    private void OpenBasicRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBasicRulesActionPerformed
        // TODO add your handling code here:
        BasicRules openRules = new BasicRules();
        openRules.setVisible(true);
    }//GEN-LAST:event_OpenBasicRulesActionPerformed

    private void OpenStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenStudentsActionPerformed
        // TODO add your handling code here:
        Characters openCharac = new Characters();
        openCharac.setVisible(true);
    }//GEN-LAST:event_OpenStudentsActionPerformed

    private void StudentPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPassActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_StudentPassActionPerformed

    private void EntryPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPassActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_EntryPassActionPerformed

    private void StudentPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPass1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_StudentPass1ActionPerformed

    private void EntryPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPass1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_EntryPass1ActionPerformed

    private void OpenMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMapActionPerformed
        // TODO add your handling code here:
        Map openMap = new Map();
        openMap.setVisible(true);
    }//GEN-LAST:event_OpenMapActionPerformed

    private void RulesAndRegulation2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesAndRegulation2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_RulesAndRegulation2ActionPerformed

    private void Note2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Note2ActionPerformed

    private void EntryPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPass2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_EntryPass2ActionPerformed

    private void Note3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Note3ActionPerformed

    private void RulesAndRegulation3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesAndRegulation3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_RulesAndRegulation3ActionPerformed

    private void StudentPass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPass3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_StudentPass3ActionPerformed

    private void MapBookamarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapBookamarkActionPerformed
        // TODO add your handling code here:
        Map openMap = new Map();
        openMap.setVisible(true);
    }//GEN-LAST:event_MapBookamarkActionPerformed

    private void BookmarkRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookmarkRulesActionPerformed
        // TODO add your handling code here:
        BasicRules openRules = new BasicRules();
        openRules.setVisible(true);
    }//GEN-LAST:event_BookmarkRulesActionPerformed

    private void BookamarkStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookamarkStudentActionPerformed
        // TODO add your handling code here:
        Characters openCharac = new Characters();
        openCharac.setVisible(true);
    }//GEN-LAST:event_BookamarkStudentActionPerformed

    private void Note4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Note4ActionPerformed

    private void RulesAndRegulation4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesAndRegulation4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RulesAndRegulation4ActionPerformed

    private void EntryPass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPass3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryPass3ActionPerformed

    private void Note5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Note5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Note5ActionPerformed

    private void RulesAndRegulation5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesAndRegulation5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RulesAndRegulation5ActionPerformed

    private void EntryPass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPass4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryPass4ActionPerformed

    private void NextStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStudentButton1ActionPerformed
        // TODO add your handling code here:
        currentStudent = StudentInfo.generateRandomStudent();

        // Update the StudentPassImage JLabel
        StudentPassImage.setIcon(new ImageIcon(currentStudent.getImage()));
        StudentLetterImage.setIcon(new ImageIcon(currentStudent.getEntryPermitImage()));

        StudentNameLabel.setText(currentStudent.getName());
        StudentContactLabel.setText(currentStudent.getContact());
        StudentNumberLabel.setText(currentStudent.getStudentNumber());
        StudentCourseLabel.setText(currentStudent.getCourse());

        // Clear other JLabels
        StudentSashay.setIcon(null);
        StudentShantay.setIcon(null);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_NextStudentButton1ActionPerformed

    private void SHANTAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHANTAYActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        // Check if a student is generated
        if (currentStudent != null && currentStudent.isStudent()) {
            // Update the JLabel with the corresponding image
            StudentShantay.setIcon(new ImageIcon(currentStudent.getInImage()));
            StudentInfo.updateScore(1); // Increment score
        } else {
            // Update the JLabel with the corresponding image
            StudentShantay.setIcon(new ImageIcon(currentStudent.getInImage()));
            StudentInfo.updateMistakes(); // Deduct score
        }
        updateScoreLabels();


    }//GEN-LAST:event_SHANTAYActionPerformed

    private void SASHAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SASHAYActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        // Check if a student is generated

        if (currentStudent == null || !currentStudent.isStudent()) {
            // Update the JLabel with the corresponding image
            StudentSashay.setIcon(new ImageIcon(currentStudent.getOutImage()));
            StudentInfo.updateScore(1); // Increment score
        } else {
            // Update the JLabel with the corresponding image
            StudentSashay.setIcon(new ImageIcon(currentStudent.getOutImage()));
            StudentInfo.updateMistakes(); // Deduct score
        }
        updateScoreLabels();

    }//GEN-LAST:event_SASHAYActionPerformed

    private void NextStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStudentButtonActionPerformed
        // TODO add your handling code here:
        currentStudent = StudentInfo.generateRandomStudent();

        // Update the StudentPassImage JLabel
        StudentPassImage.setIcon(new ImageIcon(currentStudent.getImage()));
        StudentLetterImage.setIcon(new ImageIcon(currentStudent.getEntryPermitImage()));

        StudentNameLabel.setText(currentStudent.getName());
        StudentContactLabel.setText(currentStudent.getContact());
        StudentNumberLabel.setText(currentStudent.getStudentNumber());
        StudentCourseLabel.setText(currentStudent.getCourse());

        // Clear other JLabels
        StudentSashay.setIcon(null);
        StudentShantay.setIcon(null);

        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_NextStudentButtonActionPerformed

    private void SHANTAY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHANTAY3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        // Check if a student is generated
        if (currentStudent != null && currentStudent.isStudent()) {
            // Update the JLabel with the corresponding image
            StudentShantay.setIcon(new ImageIcon(currentStudent.getInImage()));
            StudentInfo.updateScore(1); // Increment score

        } else {
            // Update the JLabel with the corresponding image
            StudentShantay.setIcon(new ImageIcon(currentStudent.getInImage()));
            StudentInfo.updateMistakes(); // Deduct score
        }
        updateScoreLabels();

    }//GEN-LAST:event_SHANTAY3ActionPerformed

    private void SASHAY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SASHAY4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        // Check if a student is generated

        if (currentStudent == null || !currentStudent.isStudent()) {
            // Update the JLabel with the corresponding image
            StudentSashay.setIcon(new ImageIcon(currentStudent.getOutImage()));
            StudentInfo.updateScore(1); // Increment score
        } else {
            // Update the JLabel with the corresponding image
            StudentSashay.setIcon(new ImageIcon(currentStudent.getOutImage()));
            StudentInfo.updateMistakes(); // Deduct score
        }
        updateScoreLabels();

    }//GEN-LAST:event_SASHAY4ActionPerformed

    private void SASHAY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SASHAY2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        // Check if a student is generated

        if (currentStudent == null || !currentStudent.isStudent()) {
            // Update the JLabel with the corresponding image
            StudentSashay.setIcon(new ImageIcon(currentStudent.getOutImage()));
            StudentInfo.updateScore(1); // Increment score

        } else {
            // Update the JLabel with the corresponding image
            StudentSashay.setIcon(new ImageIcon(currentStudent.getOutImage()));
            StudentInfo.updateMistakes(); // Deduct score
            AddPointsLabel1.setText("- " + StudentInfo.getRandomDeductionAsString());
        }
        updateScoreLabels();

    }//GEN-LAST:event_SASHAY2ActionPerformed

    private void SHANTAY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHANTAY2ActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setSelectedIndex(4);
        // Check if a student is generated
        if (currentStudent != null && currentStudent.isStudent()) {
            // Update the JLabel with the corresponding image
            StudentShantay.setIcon(new ImageIcon(currentStudent.getInImage()));
            StudentInfo.updateScore(1); // Increment score

        } else {
            // Update the JLabel with the corresponding image
            StudentShantay.setIcon(new ImageIcon(currentStudent.getInImage()));
            StudentInfo.updateMistakes(); // Deduct score
            AddPointsLabel1.setText("- " + StudentInfo.getRandomDeductionAsString());
        }
        updateScoreLabels();

    }//GEN-LAST:event_SHANTAY2ActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        // Ensure the tab starts at index 0
        jTabbedPane1.setSelectedIndex(0);
        StartingGameMenu startMenu = new StartingGameMenu();
        startMenu.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_NextButtonActionPerformed
    // Method to update student pass image

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddPointsLabel1;
    private javax.swing.JLabel AddPointsLabel2;
    private javax.swing.JLabel AddPointsLabel3;
    private javax.swing.JLabel AddPointsLabel4;
    private javax.swing.JLabel AddPointsLabel5;
    private javax.swing.JLabel AddPointsLabel6;
    private javax.swing.JButton BookamarkStudent;
    private javax.swing.JButton BookmarkRules;
    private javax.swing.JLabel CurrentPointsLabel1;
    private javax.swing.JLabel CurrentPointsLabel2;
    private javax.swing.JLabel CurrentPointsLabel3;
    private javax.swing.JLabel CurrentPointsLabel4;
    private javax.swing.JLabel CurrentPointsLabel5;
    private javax.swing.JLabel CurrentPointsLabel6;
    private javax.swing.JButton DosRulesAndRegulation;
    private javax.swing.JButton EntryPass;
    private javax.swing.JButton EntryPass1;
    private javax.swing.JButton EntryPass2;
    private javax.swing.JButton EntryPass3;
    private javax.swing.JButton EntryPass4;
    private javax.swing.JPanel GameOverPanel;
    private javax.swing.JPanel HideBar;
    private javax.swing.JButton MapBookamark;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton NextStudentButton;
    private javax.swing.JButton NextStudentButton1;
    private javax.swing.JButton Note1;
    private javax.swing.JButton Note2;
    private javax.swing.JButton Note3;
    private javax.swing.JButton Note4;
    private javax.swing.JButton Note5;
    private javax.swing.JLabel NoteImage;
    private javax.swing.JPanel NotePanel;
    private javax.swing.JButton OpenBasicRules;
    private javax.swing.JButton OpenMap;
    private javax.swing.JButton OpenStudents;
    private javax.swing.JLabel RuleBookImage;
    private javax.swing.JPanel RuleBookPanel;
    private javax.swing.JButton RulesAndRegulation;
    private javax.swing.JButton RulesAndRegulation2;
    private javax.swing.JButton RulesAndRegulation3;
    private javax.swing.JButton RulesAndRegulation4;
    private javax.swing.JButton RulesAndRegulation5;
    private javax.swing.JButton SASHAY;
    private javax.swing.JButton SASHAY2;
    private javax.swing.JButton SASHAY4;
    private javax.swing.JButton SHANTAY;
    private javax.swing.JButton SHANTAY2;
    private javax.swing.JButton SHANTAY3;
    private javax.swing.JPanel SashayPanel;
    private javax.swing.JLabel Score;
    private javax.swing.JPanel ScoreBoardPanel;
    private javax.swing.JPanel ScoreBoardPanel1;
    private javax.swing.JPanel ScoreBoardPanel2;
    private javax.swing.JPanel ScoreBoardPanel3;
    private javax.swing.JPanel ScoreBoardPanel4;
    private javax.swing.JPanel ScoreBoardPanel9;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JPanel ShantayPanel;
    private javax.swing.JLabel StudentContactLabel;
    private javax.swing.JLabel StudentCourseLabel;
    private javax.swing.JLabel StudentLetterImage;
    private javax.swing.JPanel StudentLetterPanel;
    private javax.swing.JLabel StudentNameLabel;
    private javax.swing.JLabel StudentNumberLabel;
    private javax.swing.JButton StudentPass;
    private javax.swing.JButton StudentPass1;
    private javax.swing.JButton StudentPass3;
    private javax.swing.JLabel StudentPassImage;
    private javax.swing.JPanel StudentPassPanel;
    private javax.swing.JLabel StudentSashay;
    private javax.swing.JLabel StudentShantay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    private void updateScoreLabels() {
        // Calculate the change in score
        int lastScoreChange = StudentInfo.getScore() - score;
        score = StudentInfo.getScore(); // Update the score to the current value

        // Update the score labels with the current scores
        if (lastScoreChange > 0) {
            // Score increased
            AddPointsLabel1.setText("+ " + lastScoreChange);
            AddPointsLabel2.setText("+ " + lastScoreChange);
            AddPointsLabel3.setText("+ " + lastScoreChange);
            AddPointsLabel4.setText("+ " + lastScoreChange);
            AddPointsLabel5.setText("+ " + lastScoreChange);
            AddPointsLabel6.setText("+ " + lastScoreChange);
        } else if (lastScoreChange < 0) {
            // Score decreased
            int deduction = Math.abs(lastScoreChange); // Get the deduction value
            String deductionString = "-" + deduction; // Convert to string
            // Set deduction value for AddPointsLabel1
            AddPointsLabel1.setText(deductionString);
            // Set the same deduction value for the rest of the labels
            AddPointsLabel2.setText(deductionString);
            AddPointsLabel3.setText(deductionString);
            AddPointsLabel4.setText(deductionString);
            AddPointsLabel5.setText(deductionString);
            AddPointsLabel6.setText(deductionString);
        } else {
            // No change in score
            AddPointsLabel1.setText("0");
            AddPointsLabel2.setText("0");
            AddPointsLabel3.setText("0");
            AddPointsLabel4.setText("0");
            AddPointsLabel5.setText("0");
            AddPointsLabel6.setText("0");
        }

        CurrentPointsLabel1.setText(StudentInfo.getScoreAsString());
        CurrentPointsLabel2.setText(StudentInfo.getScoreAsString());
        CurrentPointsLabel3.setText(StudentInfo.getScoreAsString());
        CurrentPointsLabel4.setText(StudentInfo.getScoreAsString());
        CurrentPointsLabel5.setText(StudentInfo.getScoreAsString());
        CurrentPointsLabel6.setText(StudentInfo.getScoreAsString());

        ScoreLabel.setText(StudentInfo.getHighScoreAsString());
        int currentScore = StudentInfo.getScore();
        if (currentScore < 0) {
            AddPointsLabel1.setText("0");
            Score gameOver = new Score();
            gameOver.setVisible(true);
            this.dispose();

        }
    }
}
